### PR TITLE
input sanitizing to avoid infinite loop

### PR DESCRIPTION
**Pull request by theflyingbear**
call with negative int as argument produced an infinite millipede.

### CODE REVIEW

**Comment by tusbar** [comment]
`size` is a `size_t` though…

**Comment by tusbar** [comment]
isn’t that unsigned?

**Comment by theflyingbear** [comment]
yes, size_t is unsigned, but atoi() returns an int.
my learning of C is bit old, but I do remember that there was some strange/dirty magic with implicit casts...

**Comment by louiz** [comment]
-1 is just converted to a very big unsigned number. So that would not be infinite, just a very big millipede.

**Comment by tusbar** [comment]
:-1:

**Comment by evadot** [comment]
atoi shouldn't be used in new code, you should use strtoul.
This kind of code make the milliepede sad ...

**Comment by tusbar** [comment]
it does. :cry:

**Comment by louiz** [comment]
But using strtoul would not fix the issue of having a huge millipede when the user specifies a negative size.

**Comment by tusbar** [comment]
:cry:

**Pull request merged**
